---
# Ergatis Component Documentation
# Extracted from source by extract_component_docs.pl
# Source: TIGR/JCVI/IGS Ergatis bioinformatics workflow system
#
# This file preserves ALL documentation, comments, parameter descriptions,
# and structural details from the original Ergatis source files.

component: prodigal
extracted_at: "2026-02-19T15:34:47"
source_files:
  - prodigal.config
  - prodigal.xml
  - prodigal.i1.xml

# Configuration file - all sections, parameters, defaults, and inline comments
config:
  interface:
    classification: feature prediction / genes
  parameters:
    # gff or gbk or sco(simple coordinates). Default is gbk
    OUTPUT_FORMAT: sco
    PRODIGAL_OPTS: -c
    TRANSLATION_TABLE: ""
    PROJECT_ABBREVIATION: ""
  input:
    INPUT_FILE_LIST: ""
    INPUT_FILE: ""
    INPUT_DIRECTORY: ""
    # the following is only used when iterating over an INPUT_DIRECTORY
    INPUT_EXTENSION: fsa
  output:
    OUTPUT_TOKEN: default
    OUTPUT_DIRECTORY: $;REPOSITORY_ROOT$;/output_repository/$;COMPONENT_NAME$;/$;PIPELINEID$;_$;OUTPUT_TOKEN$;
    STAGING_DIR: ""
    BSML_OUTPUT_LIST: $;OUTPUT_DIRECTORY$;/$;COMPONENT_NAME$;.bsml.list
    RAW_OUTPUT_LIST: $;OUTPUT_DIRECTORY$;/$;COMPONENT_NAME$;.raw.list
  component:
    COMPONENT_NAME: prodigal
    DESCRIPTION: none
    WORKFLOW_REPOSITORY: $;REPOSITORY_ROOT$;/workflow/runtime/$;COMPONENT_NAME$;/$;PIPELINEID$;_$;OUTPUT_TOKEN$;
    PIPELINE_TOKEN: unnamed
    # The version,revision,tag here is set by an interpolated CVS tag
    VERSION: 2.0
    RELEASE_TAG: $Name$
    REVISION: "$Revision: 6346 $"
    TEMPLATE_XML: $;DOCS_DIR$;/$;COMPONENT_NAME$;.xml
    ITERATOR1: i1
    ITERATOR1_XML: $;DOCS_DIR$;/$;COMPONENT_NAME$;.$;ITERATOR1$;.xml
    # Distributed options
    GROUP_COUNT: 150
    NODISTRIB: 0
    # the following keys are replaced at runtime by the invocation script
    COMPONENT_CONFIG: ""
    COMPONENT_XML: ""
    PIPELINE_XML: ""
    PIPELINEID: ""
  include:
    PROJECT_CONFIG: ""

# Main workflow XML template - step definitions
workflow_xml:
  xml_comments:
    - Preprocessing
    - Processing
    - Iterator
    - Postprocessing
  command_sets:
    - prodigal workflow
  includes:
    - "file=\"$;DOCS_DIR$;/file_iterator_template.xml\" keys=\"$;ITERATOR_NAME$;=ITERATOR1,$;ITERATOR_XML$;=ITERATOR1_XML\""
  steps:
    - name: create output directory
      type: RunUnixCommand
      executable: mkdir
      arg: -p -m 777 $;OUTPUT_DIRECTORY$;
    - name: create temp directory
      type: RunUnixCommand
      executable: mkdir
      arg: -p -m 777 $;TMP_DIR$;
    - name: create bsml list
      type: RunUnixCommand
      executable: $;BIN_DIR$;/create_list_file
      params:
        - key: --directory
          value: $;OUTPUT_DIRECTORY$;
        - key: --regex
          value: "\".*\\.bsml\""
        - key: --output_list
          value: $;BSML_OUTPUT_LIST$;
    - name: create raw list
      type: RunUnixCommand
      executable: $;BIN_DIR$;/create_list_file
      params:
        - key: --directory
          value: $;OUTPUT_DIRECTORY$;
        - key: --regex
          value: "\".*\\.predict\""
        - key: --output_list
          value: $;RAW_OUTPUT_LIST$;

# Iterator i1 - per-input processing steps
iterator_i1:
  command_sets:
    - prodigal component
  steps:
    - name: prodigal
      type: RunUnixCommand
      executable: $;PRODIGAL_EXEC$;
      arg: $;PRODIGAL_OPTS$; -f $;OUTPUT_FORMAT$; -g $;TRANSLATION_TABLE$; -i $;I_FILE_PATH$; -o $;OUTPUT_DIRECTORY$;/$;ITERATOR_NAME$;/g$;GROUP_NUMBER$;/$;I_FILE_BASE$;.$;COMPONENT_NAME$;.predict
      params:
        - key: stderr
          value: $;OUTPUT_DIRECTORY$;/$;ITERATOR_NAME$;/g$;GROUP_NUMBER$;/$;I_FILE_BASE$;.$;COMPONENT_NAME$;.stderr
    - name: prodigal2bsml
      type: RunUnixCommand
      executable: $;BIN_DIR$;/prodigal2bsml
      params:
        - key: --fasta_input
          value: $;I_FILE_PATH$;
        - key: --input_file
          value: $;OUTPUT_DIRECTORY$;/$;ITERATOR_NAME$;/g$;GROUP_NUMBER$;/$;I_FILE_BASE$;.$;COMPONENT_NAME$;.predict
        - key: --output
          value: $;OUTPUT_DIRECTORY$;/$;ITERATOR_NAME$;/g$;GROUP_NUMBER$;/$;I_FILE_BASE$;.$;COMPONENT_NAME$;.bsml
        - key: --project
          value: $;PROJECT_ABBREVIATION$;
        - key: --id_repository
          value: $;PROJECT_ID_REPOSITORY$;
    - name: store config params
      type: RunUnixCommand
      executable: $;BIN_DIR$;/analysis2bsml
      params:
        - key: --ergatis_control_file
          value: $;ERGATIS_DIR$;.ini
        - key: --conf
          value: $;COMPONENT_CONFIG$;
        - key: --bsml_file
          value: $;OUTPUT_DIRECTORY$;/$;ITERATOR_NAME$;/g$;GROUP_NUMBER$;/$;I_FILE_BASE$;.$;COMPONENT_NAME$;.bsml
        - key: --componenturl
          value: $;WORKFLOW_REPOSITORY$;/component.xml
        - key: --pipelineurl
          value: $;PIPELINE_XML$;
        - key: --analysis_id
          value: $;COMPONENT_NAME$;_analysis
    - name: dtd validation
      type: RunUnixCommand
      executable: $;BIN_DIR$;/dtdValid.pl
      arg: $;OUTPUT_DIRECTORY$;/$;ITERATOR_NAME$;/g$;GROUP_NUMBER$;/$;I_FILE_BASE$;.$;COMPONENT_NAME$;.bsml
      params:
        - key: -d
          value: $;DOCS_DIR$;/bsml3_1.dtd

# Perl script documentation (POD)
perl_scripts:
  - script: create_list_file.pl
    pod: |
  =head1	NAME
  
  create_list_file.pl - script to create a list of files given a certain regex
  
  =head1	SYNOPSIS
  
  USAGE: create_list_file.pl
         [  --directory|d=/path/to/some/directory/
            --output_list|o=/path/output.list
            --regex|r=string regular expression
            --include_gz|g ]
  
  =head1	OPTIONS
  
  B<--directory,-d>
  	Location of the directory to search.  No wild card characters should be
      used in the directory.
      (Default: current directory)
  
  B<--output_list,-o>
      File that will be the list of found files
      (Default: standard out)
  
  B<--regex,-r>
      Regular expression for entire file name (including full path)
      (Default: finds all files)
  
  B<--include_gz|g>
      This flag tells the script to include .gz extensions in the list
  
  B<--help,-h>
  	Prints this help message
  
  =head1	DESCRIPTION
  
      This script will search a directory for file names containing the given
      regular expression.  By default, all .gz or .gzip extensions are stripped
      off.  Programs using these list files should know to search for .gz|.gzip
      versions.
  
      **Note: No wild card characters should be used in this option.
  
  =head1	INPUT
  
      There are no required options to the script and there isn't really any
      input.  See above for defaults.  
  
  =head1	OUTPUT
  
      The script will output a list of files that match the regular expression
      given by option --regex|-r. If no output file is given, this script will 
      print out to standard out.  
  
  =head1	CONTACT
  
      Kevin Galens
      kgalens@tigr.org
  - script: prodigal2bsml.pl
    pod: |
  =head1 NAME
  
  prodigal2bsml.pl - Creates a bsml document from prodigal raw output
  
  =head1 SYNOPSIS
  
  USAGE: prodigal2bsml.pl
              --input_list=/path/to/some/prodigal.raw.list
              --input_file=/path/to/some/prodigal.raw
              --output=/path/to/transterm.bsml
              --id_repository=/path/to/id_repository
              --fasta_input=/path/to/prodigal/input.fsa
            [ --log=/path/to/file.log
              --debug=4
              --help
            ]
  
  =head1 OPTIONS
  
  B<--input_list,-i>
      Input list of prodigal raw output files (.predict)
  
  B<--input_file,-f>
      Input prodigal raw file (.predict)
  
  B<--output,-o>
      The output bsml file.
  
  B<--id_repository,-r>
      Id repository for use by Workflow::IdGenerator.pm
  
  B<--fasta_input,-a>
      The input file that was used as input for the prodigal run
  
  B<--log,-l>
      Logfile.
  
  B<--help,-h>
      Print this message
  
  =head1  DESCRIPTION
  
  This script is used to convert the output from a prodigal search into BSML.
  
  =head1  INPUT
  
  You define the input file using the --input option.  This file does not need any
  special file extension.  The regular output of prodigal looks like this:
  
  
  # Sequence Data: seqnum=1;seqlen=5127136;seqhdr="gec3273.pseudomolecule.11"
  # Model Data: version=Prodigal.v2.50;run_type=Single;model="Ab initio";gc_cont=50.70;transl_table=4;uses_sd=1
   >17_20759_21505_+
   >18_21508_22068_-
   >19_22103_22444_-
   >20_22579_22905_+
  
  Where the columns from left to right separated by '_' contain:
  prediction_id   start_position   end_position   strand 
  start_position is always less than the end_position
  
  =head1 OUTPUT
  
  After parsing the input file, a file specified by the --output option is created.  This script
  will fail if it already exists.  The file is created, and temporary IDs are created for
  each result element.  They are only unique to the document, and will need to be replaced
  before any database insertion.
  
  Base positions from the input file are renumbered so that positions start at zero.
  
  NOTE:
  This script is created by modifying Kevin's glimmer32bsml.pl for prodigal
  
  =head1  CONTACT
  
      Sonia Agrawal
      sagrawal@som.umaryland.edu
  - script: analysis2bsml.pl
    pod: |
  =head1  NAME 
  
  analysis2bsml.pl - add analysis parameters to a BSML result doc
  
  =head1 SYNOPSIS
  
      USAGE:  analysis2bsml.pl --bsml_file=/path/to/some/output.bsml 
                               --conf=/path/to/some/pipeline.config
                             [ --ergatis_control_file=/path/to/ergatis_install.ini ]
                             [ --componenturl=/path/to/some/pipeline.xml ]
                             [ --pipelineurl=/path/to/some/pipeline0.xml ]
                             [ --debug debug_level  ]
                             [ --log log_file ]
                             [ --analysis_id=some_id ]
  
  =head1 OPTIONS
  
  =item *
  
  B<--debug,-d> Debug level.  Use a large number to turn on verbose debugging. 
  
  =item *
  
  B<--analysis_id,-a> Analysis id (optional).  If given, will be the id attribute for the Analysis
  element created or appended to.  If the value 'first' is passed, the first Analysis element will
  be used.  If not given, the Analysis element will be created with no id attribute.
  
  =item *
  
  B<--log,-l> Log file
  
  =item *
  
  B<--help,-h> This help message
  
  =item *
  
  B<--ergatis_control_file,-e> Control file defining software versions for ergatis install.
  
  =item *
  
  B<--componenturl,-u> Stores component url in <Analysis>
  
  =item *
  
  B<--pipelineurl,-p> Store pipeline.xml url in <Analysis>
  
  =back
  
  =head1   DESCRIPTION
  
  This script is used to record the parameters of an analysis into the BSML file that the
  analysis created.  This is done to ensure that each of the run-time settings for the
  analysis are recorded for informational purposes or to re-run the analysis.
